version: '3.8'

services:
  api-gateway:
    image: traefik:v2.10
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.file.directory=/etc/traefik/
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
    ports:
      - "8888:80"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik:ro

  user-service:
    build: ./services/user_service
    volumes:
      - ./services/user_service:/app
    env_file:
      - .env
    depends_on:
      db-init:
        condition: service_completed_successfully
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped

  clinical-record-service:
    build: ./services/clinical_record_service
    volumes:
      - ./services/clinical_record_service:/app
    env_file:
      - .env
    depends_on:
      db-init:
        condition: service_completed_successfully
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped

  inference-service:
    build: ./services/inference_service
    volumes:
      - ./services/inference_service:/app
    env_file:
      - .env
    depends_on:
      db-init:
        condition: service_completed_successfully
    environment:
      - LLM_SERVER_URL=${LLM_SERVER_URL}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped

  scheduling-service:
    build: ./services/scheduling_service
    volumes:
      - ./services/scheduling_service:/app
    env_file:
      - .env
    depends_on:
      db-init:
        condition: service_completed_successfully
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped

  db-init:
    build: ./services/user_service # Or any service that has all models
    command: python -c "from app.database import engine, Base; from app.models import user; Base.metadata.create_all(bind=engine)"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: