version: '3.8'

services:
  user-service:
    build: ./services/user_service
    ports:
      - "8000:8000"
    volumes:
      - ./services/user_service:/app
    env_file:
      - .env
    depends_on:
      - db

  clinical-record-service:
    build: ./services/clinical_record_service
    ports:
      - "8001:8001"
    volumes:
      - ./services/clinical_record_service:/app
    env_file:
      - .env
    depends_on:
      - db

  inference-service:
    build: ./services/inference_service
    ports:
      - "8002:8000"
    volumes:
      - ./services/inference_service:/app

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data: